# Generated by Django 4.2.2 on 2023-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excer',
            field=models.CharField(default='', max_length=25),
        ),
    ]
