# Generated by Django 4.2.2 on 2023-06-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_excer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='excer',
            new_name='excerpt',
        ),
    ]
