# Generated by Django 4.2.2 on 2023-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_excer_blog_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
