# Generated by Django 4.2.2 on 2023-06-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(default='', max_length=50),
        ),
    ]
