# Generated by Django 4.2.2 on 2023-06-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='upload',
            new_name='Image',
        ),
    ]
